#include "../Clipp/Bridge/ClippLoggerCore.mm"
#include "../Clipp/Bridge/ClippSharedCore.mm"
#include "../Clipp/Bridge/ClippCryptoChannelCore.mm"
#include "../../src/ClipboardWire.cpp"
#include "../../src/MDNSProtocol.cpp"
#include "../../src/MDNSDiscovery_Apple.mm"
#include "../../src/OneShotPeer.cpp"
